### ISSUE TITLE
Unable to add Graph Panel to Dashboard (Banana v1.7.0)

### ISSUE THREAD

**Issue by muchivolu** [lucidworks/banana#368]
Hi,

Unable to add Graph Panel to Dashboard (Banana v1.7.0), "Add Panel" button is disabled.

**Comment by aadel** [comment]
Could you use the template below to add details about the issue:

**Description**
A clear and concise description of what the issue is.

**Regeneration**
Steps to regenerate the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Platform**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by muchivolu** [comment]
Please find the environment details below :
OS : Mac OS Catalina 10.15.4
Browser : Chrome Version 81.0
Solr : 8.0.0
Banana : 1.7.0

Navigation on Banana :  Click New --> Non-Time Series Dashboard 
                                        Given collection name: Products --> Click on Create
                                        Add Panel --> select Panel : graph 

I have provided the required details for Graph Panel, but the "Add Panel" is not becoming active (Please find the attached screenshot).

<img width="1379" alt="Screen Shot 2020-05-27 at 10 17 50 PM" src="https://user-images.githubusercontent.com/40000067/83057725-5d43f880-a068-11ea-911e-c7f539a41681.png">

**Comment by aadel** [comment]
A possibility that could case this issue is loading the graph module didn't complete properly. Are there any errors that appear in the browser console after opening the modal?
